-- MySQL Database Setup
CREATE DATABASE IF NOT EXISTS semester_marks;

USE semester_marks;

-- Results table will be auto-created by Spring Boot JPA
-- But you can manually create if needed:

CREATE TABLE IF NOT EXISTS results (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_name VARCHAR(100) NOT NULL,
    roll_no VARCHAR(50) NOT NULL UNIQUE,
    semester INT NOT NULL,
    total_marks DOUBLE,
    percentage DOUBLE,
    grade VARCHAR(5),
    status VARCHAR(10)
);

-- Sample query to view results
-- SELECT * FROM results;

-- Notes for MongoDB:
-- Use MongoDB Compass or mongo shell to create database
-- db.createCollection("results")

-- Notes for Oracle:
-- CREATE TABLE results (
--     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     student_name VARCHAR2(100) NOT NULL,
--     roll_no VARCHAR2(50) NOT NULL UNIQUE,
--     semester NUMBER NOT NULL,
--     total_marks NUMBER,
--     percentage NUMBER,
--     grade VARCHAR2(5),
--     status VARCHAR2(10)
-- );
